
"""
Django settings for template_man project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config 
import os


BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)






SECRET_KEY = 'django-insecure-mk_k*p9jnqc%qtm#8wixrzw*!n7av6@7!03$u_=y-4qps@3@i*'





INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', 
    'django.contrib.contenttypes', 
    'django.contrib.sessions', 
    'django.contrib.messages', 
    'django.contrib.staticfiles', 
    'template_api', 
    'rest_framework', 
    'django_prometheus', 
    'drf_spectacular',
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'template_api.middleware.CorrelationIdMiddleware', 
    'django_prometheus.middleware.PrometheusAfterMiddleware', 
]

ROOT_URLCONF = 'template_man.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request', 
                'django.contrib.auth.context_processors.auth', 
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug', 
            ],
        },
    },
]

WSGI_APPLICATION = 'template_man.wsgi.application'







INTERNAL_API_SECRET = config("INTERNAL_API_SECRET") 



REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'], 
    'EXCEPTION_HANDLER': 'template_api.exceptions.custom_exception_handler', 
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'template_api.authentication.InternalAPIAuthentication', 
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES':[
        'rest_framework.parsers.JSONParser',
    ]    
}




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True





STATIC_URL = 'static/'




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message} [correlation_id={correlation_id}]',
            'style': '{',
        },
        'simple': { 
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'correlation_id': {

            '()': 'template_api.logging_filters.CorrelationIdFilter',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO', 
            'class': 'logging.FileHandler', 
            'filename': os.path.join(LOG_DIR, 'app.log'), 
            'formatter': 'verbose', 
            'filters': ['correlation_id'], 
        },
        'console': { 
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple', 
            'filters': ['correlation_id'], 
        },
    },
    'root': {
        'handlers': ['file', 'console'], 
        'level': 'INFO', 
    },
   
    
}




SPECTACULAR_SETTINGS = {
    'TITLE': 'Template Service API',
    'DESCRIPTION': '''
    # Template Service API
    
    A powerful template management service for multi-channel notifications.
    
    ## Features
    - Template versioning and lifecycle management
    - Multi-language support
    - Variable substitution with {{variable}} syntax
    - Caching for high performance
    - Organization isolation (multi-tenancy)
    - Template validation
    
    ## Authentication
    Most endpoints require internal authentication via `X-Internal-Secret` header.
    Templates are scoped to organizations via `X-Organization-ID` header.
    
    **Note:** This documentation is publicly accessible without authentication.
    
    ## Template Workflow
    1. **Create** template (status: draft)
    2. **Publish** template (status: active)
    3. **Use** template in notifications
    4. **Update** template (creates new version)
    5. **Publish** new version
    6. **Archive** old templates when no longer needed
    
    ## Template Status
    - `draft` - Created but not yet active
    - `active` - Published and available for use
    - `archived` - Deactivated, no longer in use
    
    ## Versioning
    - Each update creates a new version
    - Only one version can be active at a time
    - Publishing a new version deactivates the previous one
    - All versions are retained for audit purposes
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v[0-9]',
    
    # Security schemes
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'InternalAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-Internal-Secret',
                'description': 'Internal service authentication (required for API calls, not for viewing docs)'
            }
        }
    },
    
    # No global security - docs are public
    'SECURITY': [],
    
    # Servers
    'SERVERS': [
        {
            'url': 'http://127.0.0.1:8002',
            'description': 'Development server (Template Service)'
        },
        {
            'url': 'http://localhost:8002',
            'description': 'Local server (Template Service)'
        },
    ],
    
    # UI customization
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
        'syntaxHighlight.theme': 'monokai',
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'supportedSubmitMethods': ['get', 'post', 'put', 'delete', 'patch'],
    },
    
    # Schema generation
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    
    # Tags
    'TAGS': [
        {
            'name': 'Templates',
            'description': 'Template management - create, read, update, publish, archive'
        },
        {
            'name': 'Internal',
            'description': 'Internal endpoints for gateway and worker services'
        },
        {
            'name': 'System',
            'description': 'System health and monitoring'
        },
    ],
    
 
    'CAMELIZE_NAMES': False,
    'SCHEMA_COERCE_PATH_PK': True,
}





INTERNAL_API_SECRET = config('INTERNAL_API_SECRET') 

DEBUG = config('DEBUG', default='True') == 'True'
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')





if DEBUG:
   
    DB_ENGINE_DEFAULT = 'django.db.backends.sqlite3'
    DB_NAME_DEFAULT = str(BASE_DIR / 'db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default=DB_ENGINE_DEFAULT),
            'NAME': config('DB_NAME', default=DB_NAME_DEFAULT),
           
        }
    }
else:

    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': config('DB_NAME', default='template_service_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': config('DB_HOST', default='postgres'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=600, cast=int),  # Persistent connections
        }
    }







METRICS_ENABLED = config('METRICS_ENABLED', default='True') == 'True'



TEMPLATE_CACHE_ENABLED = config('TEMPLATE_CACHE_ENABLED', default='True') == 'True'
TEMPLATE_CACHE_VERSION_KEY = config('TEMPLATE_CACHE_VERSION_KEY', default='template_cache_version')
TEMPLATE_CACHE_SYNC_INTERVAL = config('TEMPLATE_CACHE_SYNC_INTERVAL', default=300, cast=int) # Sync interval in seconds





REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/2')