# Generated by Django 4.2.26 on 2025-11-12 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique identifier for the template (e.g., welcome_email, password_reset)', max_length=255)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=500)),
                ('content', models.TextField(help_text='Template content with {{variables}}')),
                ('html_content', models.TextField(blank=True, help_text='HTML version for email templates')),
                ('language', models.CharField(db_index=True, default='en', help_text='Language code (e.g., en, fr, es)', max_length=10)),
                ('version', models.IntegerField(db_index=True, default=1)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Default version for this template/language combination')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('variables', models.JSONField(default=list, help_text='List of required variables')),
                ('optional_variables', models.JSONField(default=list, help_text='List of optional variables')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional template metadata (categories, tags, etc.)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Searchable tags for template organization')),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('usage_count', models.IntegerField(db_index=True, default=0)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('average_render_time', models.FloatField(default=0.0, help_text='Average render time in seconds')),
                ('parent_template', models.ForeignKey(blank=True, help_text='Parent template for version tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='template_api.template')),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TemplateUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(db_index=True, help_text='Template code (cached for analytics)', max_length=255)),
                ('template_version', models.IntegerField(blank=True, help_text='Template version at time of render', null=True)),
                ('notification_id', models.CharField(db_index=True, help_text='Correlation ID from notification system', max_length=255)),
                ('organization_id', models.CharField(db_index=True, help_text='Organization ID from gateway', max_length=255)),
                ('rendered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('render_time', models.FloatField(help_text='Time taken to render template in seconds')),
                ('result', models.CharField(choices=[('success', 'Success'), ('variable_missing', 'Variable Missing'), ('render_error', 'Render Error'), ('template_not_found', 'Template Not Found'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if render failed')),
                ('variables_used', models.JSONField(blank=True, default=dict, help_text='Variables actually used in render')),
                ('variables_missing', models.JSONField(blank=True, default=list, help_text='Variables that were missing')),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], db_index=True, help_text='Template type at time of render', max_length=20)),
                ('language', models.CharField(db_index=True, default='en', help_text='Language used for render', max_length=10)),
                ('template', models.ForeignKey(blank=True, help_text='Template used for this render', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='template_api.template')),
            ],
            options={
                'db_table': 'template_usage_logs',
                'indexes': [models.Index(fields=['-rendered_at'], name='template_us_rendere_503b7d_idx'), models.Index(fields=['organization_id', '-rendered_at'], name='template_us_organiz_78784d_idx'), models.Index(fields=['template_code', '-rendered_at'], name='template_us_templat_8b2a73_idx'), models.Index(fields=['result', '-rendered_at'], name='template_us_result_c23ce5_idx'), models.Index(fields=['notification_id'], name='template_us_notific_a43e8e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='templateusagelog',
            constraint=models.CheckConstraint(check=models.Q(('render_time__gte', 0)), name='render_time_positive'),
        ),
        migrations.AddConstraint(
            model_name='templateusagelog',
            constraint=models.CheckConstraint(check=models.Q(('rendered_at__lte', datetime.datetime(2025, 11, 12, 12, 36, 55, 303227, tzinfo=datetime.timezone.utc))), name='rendered_at_in_past'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['code', 'status', 'language'], name='templates_code_45787c_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['template_type', 'status'], name='templates_templat_3f0ace_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['status', '-created_at'], name='templates_status_c9fdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['-usage_count'], name='templates_usage_c_47fafd_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['language', 'is_default'], name='templates_languag_5c13a4_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['-last_used_at'], name='templates_last_us_d867bb_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['created_at'], name='templates_created_2dfe96_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['tags'], name='templates_tags_54e72a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('code', 'version', 'language'), ('code', 'language', 'is_default')},
        ),
    ]
