# Generated by Django 4.2.26 on 2025-11-13 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_api', '0002_organization_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='templateusagelog',
            name='rendered_at_in_past',
        ),
        migrations.AddConstraint(
            model_name='templateusagelog',
            constraint=models.CheckConstraint(check=models.Q(('rendered_at__lte', datetime.datetime(2025, 11, 13, 0, 51, 13, 39031, tzinfo=datetime.timezone.utc))), name='rendered_at_in_past'),
        ),
    ]
